spring:
    application:
        name: ihub

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:ihub_test}
        username: ${MYSQL_USER:test}
        password: '${MYSQL_PASSWORD:test}'

    jpa:
        open-in-view: false
        show-sql: false
        hibernate:
            ddl-auto: update # none in prod
        database-platform: org.hibernate.dialect.MySQLDialect

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true

security:
    jwt:
        secret: ${JWT_SECRET:dGVzdHRlc3R0ZXN0dGVzdHRlc3R0ZXN0dGVzdHRlc3R0ZXN0dGVzdHRlc3Q=}
        expiration-ms: 86400000

springdoc:
    swagger-ui:
        path: /api/docs
        enabled: true # false in prod
    api-docs:
        enabled: true # false in prod
